spring.application.name=api-veiculos

# 1. URL de Conexão
spring.datasource.url=jdbc:mysql://localhost:3306/api_veiculos?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# 2. Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL que o Spring está gerando no seu console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true